<?php

/**
 * Implementa hook_help().
 *
 * Muestra ayuda e información del modulo.
 *
 * @param path 
 *  En que parte del sitio estamos usando la ayuda
 * @param arg 
 *   Array que contiene la ruta actual y como se devuelve
 */
function stock_cero_help($path, $arg) {
  switch ($path) {
    case "admin/help#stock_cero":
      return t("Ayuda del modulo cero stock");
      break;
  }
}



/**
 * Implementa hook_block_info().
 * 
 */
function stock_cero_block_info() {
    $blocks['stock_cero'] = array(
      // El nombre que aparece en la lista de bloques.
      'info' => t('Cero stock'),
      // Ajustes por defecto.
      'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
  }





/**
 *Muestra el stock disponoble segun criterios
 * @param display
 *  Variable que nos dice donde estamos visualizando el stock
 *
 */
function stock_cero_contents($display) {
    

    switch ($display) {

        case 'block':
          /**
           * En el caso de ser un bloque solo se muestran
           * los que estan agotados
           */ 

        $query = db_select('field_data_commerce_stock', 'n')
        ->fields('n', array('entity_id', 'commerce_stock_value'))
        ->condition('commerce_stock_value', 0);

            break;

        case 'page':

        /**
         * En el caso de ser una pagina se van a mostrar segun el rango que le
         * pongamos
         */

        $rango = variable_get('stock_cero_rango', 0);

        /**
         * se obtiene todos los productos que le pasemos la rango, es decir si establecemos
         * que el rango maximo de stock es 3, nos va a mostrar todos los productos que tengan
         * menos de 3 en el almcacen
         */

        $query = db_select('field_data_commerce_stock', 'n')
          ->fields('n', array('entity_id', 'commerce_stock_value'))
          ->condition('commerce_stock_value', array(0,$rango),'BETWEEN');


            break;
       
    }
  
    return $query->execute();
  }


  /**
 * Implements hook_block_view().
 * 
 * Prepara el contenido del bloque
 */
function stock_cero_block_view($delta = '') {
  switch ($delta) {
    case 'stock_cero':
      $block['subject'] = t('Cero Stock');
      if (user_access('access stock_cero content')) {
        // Se hace uso de nuestra funcion para recuperar los datos
        $result = stock_cero_contents('block');
        // Array que contiene los datos a renderizar
        $items = array();
        // Itera los resultados y los crea como links
        foreach ($result as $node) {
          $items[] = array(
            'data' => l($node->bundle '../../products/' . $node->entity_id . '/edit'),
          ); 
        }
       // Se muestra si no hay contenido que mostrar
        if (empty($items)) {
          $block['content'] = t('No hay productos que mostrar.');  
        } 
        else {
          // Se muestran los datos del bloque.
          $block['content'] = theme('item_list', array(
            'items' => $items));
        }
      }
    return $block;
  }
  
}


/**
 * Implementa hook_menu().
 */
function stock_cero_menu() {
  $items = array();

  /**
   * Como se va a mostrar en el menu
   */
  $items['admin/config/content/stock_cero'] = array(
    'title' => 'Cero Stock',
    'description' => 'Configuración del modulo Cero Stock',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stock_cero_form'),
    'access arguments' => array('access stock_cero content'),
    'type' => MENU_NORMAL_ITEM,
  );

/**
 * Enlace a la pagina
 */
  $items['stock_cero_page'] = array(
    'title' => 'Cero Stock Page',
    'page callback' => '_stock_cero_page',
    'access arguments' => array('access stock_cero content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Llamda de la pagina: Cero stock ajustes
 *
 * @see cero_stock_menu()
 */
function stock_cero_form($form, &$form_state) {
  $form['stock_cero_rango'] = array(
    '#type' => 'textfield',
    '#title' => t('El numero maximo de stock'),
    '#default_value' => variable_get('stock_cero_rango', 3),
    '#size' => 3,
    '#maxlength' => 3,
    '#description' => t('El numero maximo de productos con "x" stock a mostrar'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}


/**
 * Implementa la validación del formulario desde Form API.
 * 
 * @param $form
 *   Array que contiene la información del formulario.
 * @param $form_state
 *  Guarda el estado anterior durante el proceso de relleno del formulario.
 */
function stock_cero_form_validate($form, &$form_state){
  $max_num = $form_state['values']['stock_cero_rango'];
  if (!is_numeric($max_num)){
    form_set_error('stock_cero_rango', t('Solo caracteres numericos entre 0 y 999'));
  }
  elseif ($max_num <= 0){
    form_set_error('stock_cero_rango', t('Solo carecteres numericos positivos'));
  }
}


/**
 * Implements hook_permission().
 */
function stock_cero_permission() {
  return array(
    'access stock_cero content' => array(
      'title' => t('Acceso al contenido del modulo Cero Stock'),
    )
  );
}



/**
 * LLamada a la pagina Cero Stock
 *
 * @see stock_cero_menu()
 * 
 */
function _stock_cero_page() {
  //Comprobamos los permisos
  if (user_access('access stock_cero content')) {
    // Usamos nuestra funcion para obtener datos.
    $result = stock_cero_contents('page');
    //Array que contiene elementos de la pagina a renderizar.
    $items = array();
    // Iteramos los resultados y creamos los links
    foreach ($result as $node) {
     //Creamos por cada elemento un enlace
      $items[] = array(
        l($node->title, '../../products/' . $node->entity_id . '/edit'  ),
        $node->commerce_stock_value
      );
    }
  }
  
  $page_array[] = array(
    '#title' => t('Ultimas unidades'),
    '#items' => $items,
    '#theme' => 'item_list',
    '#empty' =>t('No hay productos que coincidan con el criterio'),
  );

  return $page_array;
}